### ISSUE TITLE
Parsing `EmaBuffer`s from `Data::getAsHex()` back into messages

### ISSUE THREAD

**Issue by mattgodbolt** [Refinitiv/Real-Time-SDK#217]
It seems there's an API to get the "raw" data as binary - `getAsHex()`. This lets one turn any `refinitiv::ema::access::Data` object into the binary representation of the object.  Is there a way to  do the reverse? Given a binary array, turn it back into the appropriate `Data` object? I couldn't find any examples that use the `getAsHex()` feature. If one can't turn the binary back into a data object, what is the purpose of the `getAsHex()` ?

**Comment by L-Karchevska** [comment]
@mattgodbolt Thank you for the question! The `getAsHex()` method exists purely for debugging purposes so that the user could dump the encoded object. EMA layer doesn't support explicit decoding of data by the user and doesn't expose this functionality as in ETA layer.

NOTE. In case copying of the obtained objects is needed, EMA provides cloning functionality that performs deep copy of objects - please refer to the copy constructors, e.g.,
https://github.com/Refinitiv/Real-Time-SDK/blob/5105c85738089a935e3fcef161510bda7088658d/Cpp-C/Ema/Src/Access/Include/ReqMsg.h#L97-L101

**Comment by mattgodbolt** [comment]
In this instance I'm trying to serialise binary data to be able to parse it later in tests:

For example, if I want to test code that uses `FieldList`s I can't - if I make a `FieldList` and then `complete()` it, I can't then call `forth()` etc on it (it crashes without a `Decoder`).

I looked at the tests in the rtsdk itself and they all use low-level primitives using `rssl*` functions, and then some `Impl` `StaticDecoder()` routines that aren't part of the "public" API. This seem very complex - I was hoping I could create a test message using the creation API, and then pass it to tests that show they interpret them correctly.

Specifically:

```cpp

FieldList field_list;
field_list.complete();  // an empty field list
field_list.forth();  // this segfaults!
```

So I was trying to use the getAsHex() on a data class instead to have a message to deserialize, which doesn't work.

**Comment by L-Karchevska** [comment]
@mattgodbolt Thank you for the details! We've stored this issue as enhancement request and will implement it in the future releases. 
As for now, the way to test whether the message is encoded the right way could be to exchange the message between the provider and consumer.

**Comment by mattgodbolt** [comment]
Understood. For now I've patched rtsdk to allow me to do this.

**Comment by vlevendel** [comment]
@mattgodbolt In the upcoming release, we will provide helpers with _toString_ functionality on various containers which may be of use to you. At this juncture, we do not plan to extend EMA to provide _getAsHex_ since EMA is intended to be an ease of use layer which handles message encoding on behalf of the application. Please considering writing to ETA+Reactor layer for deserializing content.
