### ISSUE TITLE
EMA C#: UpdateMsg.Clone() in producer-consumer queue leaks memory

### ISSUE THREAD

**Issue by y-intercept2018** [Refinitiv/Real-Time-SDK#298]
C# version: .net6.0
LSEG.Ema.Core version: 3.3.0

We are advised by a member of the dev team (via a support ticket) that we should use updateMsg.Clone() to add the updateMsg to a queue, and consume it from another thread. So that the `OnUpdateMsg()` callback could return as soon as possible. However, our test shows that this paradigm does not work, somehow updateMsg.Clone() is leaking memory.

A minimally reproducible example:
```
using LSEG.Ema.Access;
using LSEG.Ema.Rdm;

internal class AppClient : IOmmConsumerClient
{
    public void OnRefreshMsg(RefreshMsg refreshMsg, IOmmConsumerEvent consumerEvent)
    {
        Console.WriteLine(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ"));
        Console.WriteLine(refreshMsg);
    }

    public void OnUpdateMsg(UpdateMsg updateMsg, IOmmConsumerEvent consumerEvent)
    {
        Console.WriteLine(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ"));
        if (consumerEvent.Closure is not Queue<UpdateMsg> q)
            throw new InvalidCastException("Unexpected closure received in callback");
        lock(q) {
            q.Enqueue(updateMsg.Clone());
        }
        
    }

    public void OnStatusMsg(StatusMsg statusMsg, IOmmConsumerEvent consumerEvent)
    {
        Console.WriteLine(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ"));
        Console.WriteLine(statusMsg);
    }
}

public static class Consumer
{
    public static void Main(string[] args)
    {
        Queue<UpdateMsg> q = new();
        OmmConsumer? consumer = null;
        try
        {
            OmmConsumerConfig config = new();


            const string dataSourceHostname = "172.23.4.5:14002";
            const string dataSourceUsername = "AP2_MFMA_HK12345";           
            consumer = new OmmConsumer(config.Host(dataSourceHostname).UserName(dataSourceUsername));

            var client = new AppClient();
            var rics = new List<string>() { "AAPL.OQ", "GS.N", ".SPX", "NVDA.OQ" };
            foreach (var ric in rics) {
                var reqMsg = new RequestMsg();
                reqMsg.DomainType(EmaRdm.MMT_MARKET_PRICE).ServiceName("hEDD");
                consumer.RegisterClient(reqMsg.Name(ric), client, q);
            }

            while (true)
            {
                var success = true;
                UpdateMsg msg;
                lock (q)
                {
                    success = q.TryDequeue(out msg);
                }

                if (!success)
                {
                    Thread.Sleep(100);
                    continue;
                }
                Console.WriteLine(msg.Name());
            }
        }
        catch (OmmException ommException)
        {
            Console.WriteLine(ommException.Message);
        }
        finally
        {
            consumer?.Uninitialize();
        }
    }
}
```
Just run the program, you will see memory use keeps growing. 

Any thoughts?

**Comment by ViktorYelizarov** [comment]
@y-intercept2018 Thank you for bringing this issue to our attention! We created an internal Jira to investigate it.

**Comment by y-intercept2018** [comment]
Hi @ViktorYelizarov , thanks for the acknowledgement. But first thing first, i wonder if any one from the LSEG Real-Time SDK dev team is able to reproduce the issue by running my sample code?

**Comment by V-Anyakin** [comment]
@y-intercept2018 we could not reproduce this issue by running a slightly modified version of the application provided above.

These modifications were to force the .NET to output memory usage info after performing a garbage collection.

Could you please provide a bit more information: what is the observed rate of memory usage growth, is the garbage collection (i.e. with the `GC.Collect()` or similar method call) run before memory usage is measured, does the memory usage grow steadily?

It is expected that the memory usage would grow after initial warmup, but most of it is reclaimed by the garbage collector afterwards.

In case if memory footprint is of concern, it can further be reduced by using the `ItemCountHint` configuration property. It can be set via an EmaConfig.xml file or via the programmatic config feature.

Please refer to the [EMACSharp_ConfigGuide.pdf](https://github.com/Refinitiv/Real-Time-SDK/blob/master/CSharp/Ema/Docs/EMACSharp_ConfigGuide.pdf) document for additional information on the library configuration.

In order to reduce memory usage even further, `RequestMsg` used to register a client can be reused:
```csharp
var reqMsg = new RequestMsg();
foreach (var ric in rics)
{
    reqMsg.Clear();
    reqMsg.DomainType(EmaRdm.MMT_MARKET_PRICE).ServiceName("hEDD");
    consumer.RegisterClient(reqMsg.Name(ric), client, q);
// ....
}
```

With kind regards

**Comment by y-intercept2018** [comment]
i did the test a few more times, it is indeed not leaking--just it grows for quite a while, ~10 minutes, before releasing memory, even if I manually call `GC.Collect()`
