### ISSUE TITLE
EMAJ: Allow EmaConfig.xml to be loaded from jar's resource

### ISSUE THREAD

**Issue by anthonyay** [Refinitiv/Real-Time-SDK#69]
Currently, in EMAJ 1.2.0, the ConfigReader.loadFile(String) uses File class to read the EMAConfig.xml file, which doesn't work when the config is bundled with the jar as a resource.

Could you please make a change so that a resource can be loaded as well? Like changing it to use URI or URL instead of File, something like URL(classpath:/config/blah/EmaConfig.xml) ?

**Comment by bberner** [comment]
Thank you for your feedback.  The existing functionality of ConfigReader.loadFile(String) will work if the EMAConfig.xml file is extracted from the jar file. Modifying ConfigReader.loadFile(String) to load from a URL instead of a file is an enhancement to EMA. A JIRA issue has been opened and added to the backlog. The enhancement will be considered for a future release.

**Comment by mattpeacock** [comment]
Hi,
this issue affected a few projects in my company too. 
I have raised a PR https://github.com/Refinitiv/Elektron-SDK/pull/126
thanks,
Matt

**Comment by vlevendel** [comment]
@mattpeacock Tag, Real-Time-SDK-1.5.1.L1, resolves this issue.
