### ISSUE TITLE
'make install' doesn't do anything

### ISSUE THREAD

**Issue by timrae** [Refinitiv/Real-Time-SDK#73]
Question: How am I supposed to install this library after building?

# Expected behavior
When I perform the following steps, I expect the necessary headers and libraries of the C++ versions of EMA / ETA to be installed to my `CMAKE_INSTALL_PREFIX`. 

```
mkdir build
cd build
cmake ..
make
make install
```

# Actual behavior
`make install` returns successfully but no files were installed anywhere

# Other information
* compiling from master branch
* using Linux, Centos 7.5
* cmake 3.11

**Comment by timrae** [comment]
Thank you.

I'd also like to request that you generate a cmake package config file with the installation, so we can get an imported target with all the transitive includes, flags, etc:

```cmake
find_package(libema CONFIG REQUIRED)
target_link_libraries(myexe libema)
```

**Comment by vlevendel** [comment]
@timrae We understand that cmake install will make it easy for you to find the relevant header files and libraries . We will not provide this feature at this time since the typical user of APIs will build libraries on their platform. Also, the cmake provided here is intended to integrate with application cmake build. Closing this request for now and may re-open if there is further demand. Thank you for taking the time to make this request.

**Comment by nqf** [comment]
I also think cmake install is a necessary function，
