### ISSUE TITLE
C# version out of preview

### ISSUE THREAD

**Issue by msnelling** [Refinitiv/Real-Time-SDK#95]
When can we expect the C# API to move out of preview and into the main releases?

**Comment by vlevendel** [comment]
@msnelling C# API on preview branch is a proof of concept. At this time, there are no plans to take it forward.

**Comment by AlphaGremlin** [comment]
Since there's no native support or existing interop solution, I've been building a C# interop (via P/Invoke) library for the ETA.
- .Net Core 2.1 and Framework 4.7.1 compatible
- Linux and Windows compatible
- NuGet package with native dependencies included
- 64-bit only
- C# idioms wherever possible (enums, lists, nullable message properties, etc)

I've got a good proportion of the API surface area covered, but there are gaps since I've only been mapping pieces as I come across the need for it. It's enough to reimplement the WatchlistConsumer example, and much of VaConsumer too.

At this point it's an internal project, though. I'd need to talk to my employer about open sourcing it.

**Comment by msnelling** [comment]
@vlevendel that is disappointing to say the least. What would be the best channel to request that this become a fully supported API?
We are currently using the older C# RFA API and now don't have a clear transition path to the newer Elektron-SDK.

**Comment by emirsubasic** [comment]
@msnelling did you get any more clarity on this?
@vlevendel I am really surprised that .NET is not supported. Can you please provide any more clarity on the decision not to take the C# API forward? Has anything changed since last comment from a year ago?

Thanks

**Comment by umernalla** [comment]
I will leave it to @vlevendel to provide the official response in terms of Elektron-SDK

However, depending on your requirement in terms of watchlist size and performance requirements, you may find that the Refinitiv Data Platform library may be a suitable way forward in terms of C# library..
[Article on Refinitiv Data Platform Library](https://developers.refinitiv.com/article/discover-our-refinitiv-data-platform-library-part-1)
[Overview of Refinitiv Data Platform Library](https://developers.refinitiv.com/refinitiv-data-platform/refinitiv-data-platform-libraries)

**Comment by emirsubasic** [comment]
@umernalla , my requirement is to be able to contribute (TRCC) data back for my designated RICs in .NET. In order to do that I understand I would need the Elektron SDK. I had a glance through the Refinitiv Data Platform Library and didn't spot anything about contributing data. Perhaps I missed it and maybe you can provide a more specific link?
Thanks

**Comment by umernalla** [comment]
@emirsubasic - you are correct there is currently no TRCC support in the Refinitv Data Platform library.
